### ISSUE TITLE
[db] Add support for PostgreSQL

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#10]
**Is your feature request related to a problem? Please describe.**
At present only SQLite is supported. The project needs to support other databases as well. 

**Describe the solution you'd like**
Start with adding support for PostgreSQL as an alternative. The connection can be insecure for now. We can add security in a security features phase in project development timeline. 

**Describe alternatives you've considered**
None

**Additional context**
This will require adding support for command line options for PostgreSQL connection. Perhaps add support for a quick and dirty configuration using a DB `dsn` uri.

**Comment by rareddy** [comment]
This is supported natively by the MLMD server directly now, no longer a concern. Will revisit at later time.

**Comment by tarilabs** [comment]
Reopening might come in handy for "later times", will add label for these kind of issues, shortly.
