### ISSUE TITLE
Define interactions with model serving environment to deploy and manage a model status

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#104]
Can we define a sequence diagram or interaction diagram of how model registry and Model Server going to interact for model deployment and model status management?

**Comment by dhirajsb** [comment]
Created an initial sequence diagram to show model serving interaction:
![image](https://github.com/opendatahub-io/model-registry/assets/181691/a69de262-3f58-4c96-a050-455fa8db8da9)

**Comment by rareddy** [comment]
@dhirajsb thank you. Can you give me a link to the original file, I am not able to zoom in and look at the details.

**Comment by rareddy** [comment]
@dhirajsb qq. On the `ServeModel` interactions, whyn't "Model Registry" directly read the status from the API server about `InferenceService`? thinking that would avoid any duplication of data and keep them in sync. I understand it is an extra hop in the model registry, but still not acting like any kind of controller.

**Comment by dhirajsb** [comment]
@lampajr @tarilabs we need to add a couple of more endpoints to update `ServeModels`, and make it easier to list all `ServeModels` for a `ServingEnvironment` to `model-registry.yaml`.

**Comment by dhirajsb** [comment]
> @dhirajsb thank you. Can you give me a link to the original file, I am not able to zoom in and look at the details.

I added the link in the architecture doc. 

>@dhirajsb qq. On the ServeModel interactions, whyn't "Model Registry" directly read the status from the API server about InferenceService? thinking that would avoid any duplication of data and keep them in sync. I understand it is an extra hop in the model registry, but still not acting like any kind of controller.

We should keep the business logic of how to map Kubernetes resources/status to MR metadata out of the MR itself. Since model-serving owns `ServeModel`, it's responsible for creating and keeping them updated. 
Besides, model controller should be already updating status in Kubernetes InferenceService CRs, so it's a natural place where they could also easily update the MR `ServeModel` status.

**Comment by rareddy** [comment]
> We should keep the business logic of how to map Kubernetes resources/status to MR metadata out of the MR itself.

Fair enough! (I always dislike when information is duplicated as it blurs who the master is.)

`ServeModel` is an association of `ModelVersion` and `ServingEnvironment` with having `Status` of a model as I gather from it. Can we call this something like `DeployedModel`?

I see `ServeModel` as an `Execution` type, and `InferenceService`  and `ServingEnvironment` as `Context` in MLMD terms.

**Comment by rareddy** [comment]
@Jooho @Xaenalt @israel-hdez please check above flow to create an inferencing service from the model registry. If there are any additional steps that we may have missed that would be useful.

**Comment by israel-hdez** [comment]
> @Jooho @Xaenalt @israel-hdez please check above flow to create an inferencing service from the model registry. If there are any additional steps that we may have missed that would be useful.

FWIW, I remember looking at the diagram and could not identify any gaps.

**Comment by dhirajsb** [comment]
Closing, as an initial version of the interaction has been defined. Please create new issues to refine specific parts of the interaction.
