### ISSUE TITLE
Implement Model Serving API in the GO Core layer

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#107]
**Is your feature request related to a problem? Please describe.**
Implement remaining serving api in the Model Registry core layer, i.e., here https://github.com/opendatahub-io/model-registry/blob/main/internal/core/core.go.

**Describe the solution you'd like**
Acceptance Criteria:
- Following up https://github.com/opendatahub-io/model-registry/issues/58, implement remaining operations that are related to the serving part.
- Try to keep the implementation as close as possible to the [openapi spec definition](https://github.com/opendatahub-io/model-registry/blob/main/api/openapi/model-registry.yaml) as already done for `model registration` operations.
- implementing `upsert`, `getById`, `getByParams` and `get` for the following internal/openapi models:
  - `ServingEnvironment`
  - `InferenceService`
  - `ServeModel`
- And obviously the corresponding MLMD schema mapping, i.e., how we are going to map those models into ml-metadata, exactly as we did for `RegisteredModel` [1] and the other models as well.

[1] https://github.com/opendatahub-io/model-registry/blob/main/internal/core/api.go#L20-L24

**Describe alternatives you've considered**
n/a

**Additional context**

Keep into consideration sequence diagram provided at https://github.com/opendatahub-io/model-registry/issues/104, which describes a possible interaction with the serving.

**Comment by lampajr** [comment]
Suggest to start working on this once https://github.com/opendatahub-io/model-registry/pull/85 got merged in order to have good starting point for the testing.

**Comment by rareddy** [comment]
@lampajr can you list what operations may be missing, I just want to make sure what you mean by serving matches with what is in #104 or something different.

**Comment by lampajr** [comment]
it would be about implementing `upsert`, `getById`, `getByParams` and `get` for the following internal/openapi models:
- `ServingEnvironment`
- `InferenceService`
- `ServeModel`

And obviously the corresponding MLMD schema mapping, i.e., how we are going to map those models into ml-metadata, exactly as we did for `RegisteredModel` [1] and the other models as well.

[1] https://github.com/opendatahub-io/model-registry/blob/main/internal/core/api.go#L20-L24
