### ISSUE TITLE
Create higher level Python APIs for user

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#129]
**Is your feature request related to a problem? Please describe.**
Python APIs are currently defined at par with GO APIs that are more focused on the lower level logical layer of the Model Registry. 

**Describe the solution you'd like**
For user usability purposes, to be used in the Notebooks and Pipeline components should encapsulate these lower-level APIs into functional calls like `register_model` or `list_registered_models` etc.   First, figure out the API and define it here in the issue. once there is acceptance on API then follow up with implementation and testing of the API

**Additional context**
Consider looking at other popular open source model registries to get inspiration about the type of calls to expose

**Comment by antisaling** [comment]
## First iteration proposal

As raised by @tarilabs on #158, the Python client doesn't have a strict mapping with the Go layer yet. This should be fixed so we can introduce a new abstraction layer for users of the Python client.

Having that in mind I'll propose that we adopt the following API for the first iteration:

```py
from model_registry import ModelRegistry

# these could be set by env variables
registry = ModelRegistry(address="server-address", port="port", author="author")

model = registry.register_model("my-model",
                    "s3://path/to/model",
                    format_name="onnx",
                    format_version="v1",
                    secret_account_name="access",
                    version="v2.0",
                    version_description="lorem ipsum",
                   )

model = registry.get_registered_model("my-model")

version = registry.get_model_version("my-model", "v2.0")

experiment = registry.get_model_artifact("my-model", "v2.0")
```

## Next steps

From what I've seen other clients do, a better interface could be like:

```py
model = registry.models.new("my-model")

version = model.versions.new("v2.0", description="improved inference time")

version.model.new("s3://path/to/model", format_name="onnx", format_version="v1", description="lorem ipsum")
version.tags = ["kind:onnx", "fast"]
version.metadata = {"foo": "bar"}

# version.artifacts.new(...)
```

Please let me know your opinion on this.

**Comment by rareddy** [comment]
What does Python language patterns say about or which one is a common pattern between two?

**Comment by antisaling** [comment]
> What does Python language patterns say about or which one is a common pattern between two?

The second pattern is more intuitive, but its semantics are centered around REST APIs -- think that you'd try to mimic REST routes using classes, and the endpoints are methods.

While REST might be a little cleaner from my perspective, this is very different from `mlflow`'s approach, too, so I'm not entirely sure on the best approach for the MR client.

**Comment by rareddy** [comment]
The way I see it is how you are exposing the Python API, nothing to do with REST API or not. if you want to expose flow API or functional API. The choice is in your implementation layer.

Can you give an example of `mlflow` approach?

@dtrifiro what do you recommend?

**Comment by rareddy** [comment]
@isinyaaa is this considered done and can be closed?
