### ISSUE TITLE
[feature][service] Create a DB service interface

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#13]
**Is your feature request related to a problem? Please describe.**
All DB CRUD operations should be consolidated in a single _stateless_ DB access service. 

**Describe the solution you'd like**
Create an interface for Store access `internal/service/store_service.go` that looks like:
```
type StoreService interface {
        func PutArtifact(ctx context.Context, value *db.Artifact) (*db.Artifact, error)
        func GetArtifact(ctx context.Context, query interface{}, args ...interface{}) (*db.Artifact, error)
}
```
Keep the interface close to the DB implementation for now, i.e. with the `query` and `args` style for where conditions. Also, start with a simple service for now that doesn't bring in relationships for searches right away. 
The functions should handle properties that are owned by the metadata entity, since they will be needed most of the time with the underlying artifact. 

Provide a DB implementation `internal/service/db_service.go` that looks like:
```
type DBService struct {
}
func (s *DBService) PutArtifact(ctx context.Context, value *db.Artifact) (*db.Artifact, error)
func (s *DBService) GetArtifact(ctx context.Context, query interface{}, args ...interface{}) (*db.Artifact, error)
```
The `context.Context` parameter will contain a `*gorm.DB` created by an interceptor (`middleware` in go http servers). See `db_context.go` for more details. 

**Describe alternatives you've considered**
None

**Additional context**
The service will be used in fleshing out the gRPC implementation in`grpc_server.go`. 
The StoreService interface and the DBService implementation will evolve over time so keep it simple to start and see what our search and relationships handling needs turn out to be in the future.

**Comment by tarilabs** [comment]
closing as "not planned now" and labelled as requested, per Scrum decision 2023-10-30
