### ISSUE TITLE
Creating a pip installable package for Python APIs

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#130]
**Is your feature request related to a problem? Please describe.**
We need a way to import Python libraries into a Notebook or Pipeline component

**Describe the solution you'd like**
Make Model Registry Python available as a `pip` based package

**Describe alternatives you've considered**
[Python: Creating a pip installable package](https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/#:~:text=Inside%20that%20package%20directory%2C%20alongside,be%20installed%20and%20become%20importable.)

**Comment by antisaling** [comment]
The package is now published at https://pypi.org/project/model-registry/0.1.0/.
