### ISSUE TITLE
Move `runtime` from Artifact to InferenceService

### ISSUE THREAD

**Issue by tarilabs** [opendatahub-io/model-registry-bf4-kf#131]
As noted by during Scrum 2023-10-07, there is a need to move the `runtime` from currently `Artifact` entity:

https://github.com/opendatahub-io/model-registry/blob/958630a33cac0c5686eb16df5731ab3abcd270e9/api/openapi/model-registry.yaml#L1321-L1334

to the `InferenceService` entity.

**Comment by dhirajsb** [comment]
lgtm

**Comment by dhirajsb** [comment]
@isinyaaa is there a complimentary commit to add the property to `InferenceService`?

**Comment by antisaling** [comment]
@dhirajsb I can fix that too, but this commit belongs to PR #132 .

**Comment by dhirajsb** [comment]
Ok, just making sure we don't forget about moving it to the right place.
