### ISSUE TITLE
[feature] Create a test suite runner for Python test clients

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#14]
**Is your feature request related to a problem? Please describe.**
Need a test runner for a Python test suite to run one or more Python test client scripts against the server. 

**Describe the solution you'd like**
A simple way to run integration tests using something like `make test/integration` is needed. Python probably has a JUnit style test runner facility that can run one or more Python tests. It will be useful if the runner can also start a test go server and shutdown at the end of integration tests. 

**Describe alternatives you've considered**
Current alternative of running a single Python test client is not very useful. 

**Additional context**
Integration tests are more useful at this point than unit tests to make sure all the major happy paths and scenarios for calling the server APIs work as intended.

**Comment by dhirajsb** [comment]
@isinyaaa perhaps you are best suited to start this with your previous Python experience.

**Comment by dhirajsb** [comment]
You probably already knew about it but if you didn't check out [behave](https://behave.readthedocs.io/en/latest/) for BDD in Python.

**Comment by rareddy** [comment]
@isinyaaa have you figured out how you want to write the behavior tests and what also what @dhirajsb asking above?

**Comment by tarilabs** [comment]
Sorry to interject, I'd suggest to possibly consider Robot Framework for BDD as well for the Python SDK (as in addition to User Story over REST), as the initial findings in https://github.com/opendatahub-io/model-registry/pull/108#pullrequestreview-1701740430 are promising

**Comment by rareddy** [comment]
Is this can be closed  @isinyaaa ??
