### ISSUE TITLE
[feature] Create container image in Quay

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#15]
**Is your feature request related to a problem? Please describe.**
Need a container image in Quay to be able to easily deploy the server in a cloud environment. 

**Describe the solution you'd like**
A quick and easy image is needed to start in Quay. It should use a simple `Dockerfile` to be able to stand up a model-registry server. 
The container shouldn't need anything else besides the server executable and some default params or config to get it going. To make it easy to get started the server executable should default to a SQLite database. 

@rareddy do we need an org for MR in Quay, or is there an ODH org we should re-use? We'll also need credentials to push our images to Quay. 

**Describe alternatives you've considered**
None

**Additional context**
This image is a prerequisite for creating a controller to deploy the model-registry in ODH platform.

**Comment by rareddy** [comment]
Quay bot account has been set up for pushing the images to `https://quay.io/organization/opendatahub` 
ENV variables
```
QUAY-USERNAME
QUAY_PASSWORD
```
Please set up a GHA to push the image.

**Comment by lampajr** [comment]
I took inspiration from what have been done on data-science-pipeline-operator and I created https://github.com/opendatahub-io/model-registry/pull/72 aiming to automate the build and push to quay using the provided credentials.
