### ISSUE TITLE
Use `can_add_fields` option when creating/updating mlmd types

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#159]
**Describe the bug**
If a DB exists with an older version of an mlmd type being used in the registry and a new property is being added, it throws the following error:

```
W1116 16:35:16.810298    10 metadata_store_service_impl.cc:219] PutContextType failed: Type already exists with different properties: can_add_fields is false while the given type has more properties: stored_type: id: 14
name: "odh.InferenceService"
properties {
  key: "description"
  value: STRING
}
properties {
  key: "model_version_id"
  value: INT
}
properties {
  key: "registered_model_id"
  value: INT
}
properties {
  key: "serving_environment_id"
  value: INT
}
; other_type: name: "odh.InferenceService"
properties {
  key: "description"
  value: STRING
}
properties {
  key: "model_version_id"
  value: INT
}
properties {
  key: "registered_model_id"
  value: INT
}
properties {
  key: "runtime"
  value: STRING
}
properties {
  key: "serving_environment_id"
  value: INT
}
```

**To Reproduce**
1. Use the operator to deploy the registry in a PG db in a pvc.
2. Update a type to add a new property
3. This should throw the above error

**Expected behavior**
Registry should automatically update existing mlmd types. 

**Additional context**
Check other options supported in the Put* calls for any other related use cases.

**Comment by lampajr** [comment]
Good catch @dhirajsb, going to fix that!
