### ISSUE TITLE
Include GoLang tests in GitAction/Runner

### ISSUE THREAD

**Issue by tonyxrmdavidson** [opendatahub-io/model-registry-bf4-kf#196]
Using a gitAction/Runner to call the existing quay.io image and run the GoLang tests. Task 7 from https://github.com/opendatahub-io/model-registry/issues/187

**_Definition of Done_**

When the pushed image can be pulled, all GoLang existing tests are run, all tests are passed and all relevant feedback is available for the engineer.

**Comment by rkubis** [comment]
Completed.
