### ISSUE TITLE
Version the metadata of model along with model itself

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#21]
**Is your feature request related to a problem? Please describe.**

When a Model is saved into the Model Registry/S3 alongside the Model all the metadata needs to be versioned with the same version number, these need to go together.

**Describe the solution you'd like**
Maybe once the metadata and model is added make the record immutable. If we need to change anything spin a different version of it.

**Comment by dhirajsb** [comment]
Closing as we have the model versions defined in REST API.
