### ISSUE TITLE
Improve error management when providing wrong entity

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#217]
**Is your feature request related to a problem? Please describe.**
Improve the error management whenever the wrong entity is passed in any call, i.e., whenever the user provide the parent resource Id of an entity that is different from the expected one. 

In these cases the returned error is something like:
```
"invalid TypeId, expected 11 but received 10"
```

**How to reproduce**

Startup the model registry:
```bash
docker compose -f docker-compose.yaml up
```

Create a registered model:
```bash
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/registered_models' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "MyModel",
  "state": "LIVE"
}'
```

Create model version:
```bash
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/model_versions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "v1",
  "state": "LIVE",
  "registeredModelID": "1"
}'
```

Try to create a model artifact by wrongly passing the registered model id (i.e., `1`) instead of the model version one (i.e., `2`):
```bash
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/model_versions/1/artifacts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "state": "UNKNOWN",
  "name": "v1-artifact",
  "artifactType": "model-artifact"
}'
```

You will get the error:

```bash
{
  "message": "invalid TypeId, expected 11 but received 10"
}
```

The error itself is right as the mapper is expecting a `ModelVersion` (type id `11` in this case) but it received a `RegisteredModel` (type id `10`) but it is not so easy to understand for external users, furthermore those type IDs are "internal" and do not have any meaning outside MLMD.

**Describe the solution you'd like**
My expectation would be to return an error like `invalid entity, expected ModelVersion but received RegisteredModel as parent resource. please check the provided id`.

To fix this we should keep track (internally) of the mapping between the MLMD type IDs and the corresponding entity name, this way it would be easy to provide a meaningful error msg.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rareddy** [comment]
```
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/model_versions/1/artifacts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "state": "UNKNOWN",
  "name": "v1-artifact",
  "artifactType": "model-artifact"
}' 
```
why even ask for the artifact type in this case, can this be gleaned from the path?

**Comment by lampajr** [comment]
> why even ask for the artifact type in this case, can this be gleaned from the path?

+1 I noticed the same, I opened a different issue for that: https://github.com/opendatahub-io/model-registry/issues/218

**Comment by tarilabs** [comment]
@rareddy I believe that was the same comment we had here: https://github.com/opendatahub-io/model-registry/pull/108#discussion_r1374559417
