### ISSUE TITLE
Getting `unsupported artifactType` in v1alpha1/model_versions/<id>/artifacts

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#218]
**Describe the bug**

**To Reproduce**
1. Startup the model registry:
```bash
docker compose -f docker-compose.yaml up
```

2. Create a registered model:
```bash
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/registered_models' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "MyModel",
  "state": "LIVE"
}'
```

3. Create model version:
```bash
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/model_versions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "v1",
  "state": "LIVE",
  "registeredModelID": "1"
}'
```

Create artifact without providing `artifactType`:
```bash
curl -X 'POST' \
  'http://localhost:8080/api/model_registry/v1alpha1/model_versions/2/artifacts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "state": "UNKNOWN",
  "name": "v1-artifact"
}'
```

You will get the error:

```bash
"unsupported artifactType"
```

**Expected behavior**
My expectation was that the `artifactType` would have been inferred and pre-filled automatically with `model-artifact` as right now this is the only valid artifact type.

I think the root cause here is that `api/model_registry/v1alpha1/model_versions/<id>/artifacts` accepts a generic `Artifact` and not the specific `ModelArtifact`, see https://github.com/opendatahub-io/model-registry/blob/bf56ee21940d0c302e59f68974d84fb2e3f2ffa1/api/openapi/model-registry.yaml#L419

**So here I think we have two options:**
1. Just accept `ModelArtifact` exactly as already did for plain artifacts endpoints
    - pros: the behavior will be exactly the same as the plain model artifact endpoints
    - cons: if at some point we extend the number of artifact types we might have to change the API
2. Fill that field with `model-artifact` at proxy level (as long as we know there is just one artifact type)
    - pros: easy to do and we do not have to change the API if new artifact types come in, just need to handle different types
    - cons: we have to hardcode that value 

PS: I remember the same issue was raised in some older PR but I could not find it :(

**Additional context**
n/a

**Comment by lampajr** [comment]
IMO if we are planning to extend the number of `Artifact` types other than `ModelArtifact` I would go for option 2 as temporary workaround. Otherwise if we think that `ModelArtifact` would remaing the only artifact type associtated to model versions then I think option 1 is better.

**Comment by tarilabs** [comment]
> PS: I remember the same issue was raised in some older PR but I could not find it :(

also ref https://github.com/opendatahub-io/model-registry/pull/108#discussion_r1374559417

**Comment by tarilabs** [comment]
Personally my vote like in [previous PR comments](https://github.com/opendatahub-io/model-registry/pull/108#discussion_r1374559417) would be to opt for 1.

I'm not against 2 either, but I would slightly modify for it to behave ~like: "if the user did not supply, always assume implicitly `model-artifact` for the valorization" (if feasible to "hardcode" behaviour in some of the layers)

**Comment by dhirajsb** [comment]
> My expectation was that the artifactType would have been inferred and pre-filled automatically with model-artifact as right now this is the only valid artifact type.
I think the problem is with the assumption that it should be inferred. It's perfectly valid to expect users to send the discriminator with the request, as it's also a required property. Which makes the example requests invalid with the schema. 
We have to keep the endpoint generic, because PM use cases included a scenario for MVP where they wanted to upload a README with models. We didn't have time to implement it this year, but we should be able to add that before summit.

**Comment by lampajr** [comment]
>It's perfectly valid to expect users to send the discriminator with the request, as it's also a required property. Which makes the example requests invalid with the schema.

I agree on keeping the endpoint as generic as possible, this way we can extend with new Artifacts at later point.

Given that, I think we **should improve a little bit the openapi spec** with either some concrete examples of the `ArtifactType` as right now those information are not really showed or easy to find for an user. E.g., in the swagger interface if you try to use the `/api/model_registry/v1alpha1/model_versions/{modelversionId}/artifacts` endpoint, the suggested body DOES NOT contain `artifactType` in their properties and as you said this makes the suggested body actually an `invalid` body.

Possible improvements:
1. Add a concrete example of `Artifact` object containing the discriminator value (filled with `model-artifact`)
2. Investigate if there is some issues in actual discriminator spec that is preventing to automatically put that property in the autogenerated example

**Comment by antisaling** [comment]
This is no longer an issue as there are multiple artifact types, and thus the field needs to be specified on POST.
