### ISSUE TITLE
InferenceService state terminology

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#229]
**Is your feature request related to a problem? Please describe.**
Right now for `InferenceService` entities we do have a state which can have two different possible values `DEPLOYED` and `UNDEPLOYED`. 

Since these entities are intended to be used to describe the `intention to deploy/undeploy a model` and not the deployment state itself, I think that the values could be misleading.

**Describe the solution you'd like**
 I think we should slightly change the possible values to properly keep track of correct IS states:
- `READY_TO_DEPLOY`: represents the intention to deploy an InferenceService (this will be considered by the model controller)
- `DEPLOYED`: this is going to be updated by the model controller, just to avoid that IS actually deployed will remain in READY_TO_DEPLOY state.
- `READY_TO_UNDEPLOY`: intention to undeploy a deployed model (considered by model controller)
- `UNDEPLOYED`:  _[optional]_ represents a not deployed model, we could use _nil_ state instead.

**Describe alternatives you've considered**
n/a

**Additional context**
Model controller operation are still tracked/audited using `ServeModel` entities, one per deployment.

**Comment by tarilabs** [comment]
following other k8s conventions, I would consider "deploying", "undeploying" for the interim stages

**Comment by lampajr** [comment]
> following other k8s conventions, I would consider "deploying", "undeploying" for the interim stages

I am not fully conviced as `deploying/undeploying` are intended to be set by users (either through dashboard or api) _representing their intention to deploy/undeploy a model_, therefore it is not a state set by the controller keeping track of the live resource state but it is just a manually user provided "directive" to do something.

BTW that is definitely another option to consider, thanks for sharing!

**Comment by dhirajsb** [comment]
@lampajr your assessment is right, the InferenceService metadata is what the user wants. So it shouldn't be used to reflect the state of the underlying CR. 
For that matter, we can't really completely reflect the _current_ state of the CR. MR should only record the action taken by odh-model-controller to deploy/undeploy the CR. 
It should add a link to the actual underlying CR K8s resource, so users can use K8s to get it's status and conditions. MR shouldn't be in the business of replicating _all_ functionality in K8s CRs in MR resources.

**Comment by dhirajsb** [comment]
I forgot to also mention that the deployment action state is already represented by `ServeModel.state`.

**Comment by lampajr** [comment]
> I forgot to also mention that the deployment action state is already represented by `ServeModel.state`.

+1 already using it in the odh-model-controller implementation

> the InferenceService metadata is what the user wants. So it shouldn't be used to reflect the state of the underlying CR.

Exactly, that is why I am proposing to change the InferenceService state enum values.
After some additional discussion we came up with these new possible values:

- `MARKED_FOR_DEPLOYMENT`
- `MARKED_FOR_UNDEPLOYMENT`
In addition to the already existing `DEPLOYED` and `UNDEPLOYED`.

I think that with these new `MARKED_FOR_*` values we can better describe that this state is a user "intention". Wdyt @dhirajsb ?

PS: thanks @tarilabs for these new values suggestion :pray:

**Comment by lampajr** [comment]
As agreed on scrum, we will go with this approach that technically would mean adding two new enum values:
- MARKED_FOR_DEPLOYMENT
- MARKED_FOR_UNDEPLOYMENT

Note: once this is done we should adapt the odh-model-controller behavior to use and properly update the IS state

**Comment by lampajr** [comment]
@dhirajsb were you suggesting to go with the following proposal here:
- Keep the already existing enum values
- Change the property name from `state` to `desiredState` to highlight this is a desired state set by the user. This will require change on openapi spec and in mlmd properties.

Am I right?

If so I think this is a valid alternative and I agree on proceeding this way, wdyt guys?

**Comment by lampajr** [comment]
> If so I think this is a valid alternative and I agree on proceeding this way

In the meantime I prepared a draft PR with this approach: https://github.com/opendatahub-io/model-registry/pull/243
