### ISSUE TITLE
Establish GitHub build

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#24]
**Is your feature request related to a problem? Please describe.**

Establish a continuous build for the project on GitHub 

**Describe the solution you'd like**

When a commit is pushed to GitHub an automatic build needs to occur using TravisCI or CircieCI like tools to check validity and run tests. Maybe we can use just GitHub Actions

**Comment by tarilabs** [comment]
@rareddy I believe this was already done with:
- https://github.com/opendatahub-io/model-registry/pull/6

There are followups already for improvements (e.g.: #16 and #20).

Hence I'm going to close this based on the aboves, but feel free to reopen if anything else you believe is missing.

**Comment by rareddy** [comment]
can we put some build status indicator icons on readme?

**Comment by tarilabs** [comment]
> can we put some build status indicator icons on readme?

suggesting to do once GHA is significative, per https://github.com/opendatahub-io/model-registry/issues/28
