### ISSUE TITLE
Create additional Artifact types

### ISSUE THREAD

**Issue by antisaling** [opendatahub-io/model-registry-bf4-kf#263]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to import arbitrary metadata as only model artifacts can be created on the store.

**Describe the solution you'd like**
New artifact types should be introduced so that users can store arbitrary metadata on object-storage and reference them by URI as we already do for models.

**Describe alternatives you've considered**
Importing arbitrary metadata values as MLMD fields has proven unfeasible due to DB constraints (max index size is 8191).

**Additional context**
Related: #218, #133, #260

**Comment by antisaling** [comment]
As discussed, we should have a `DocArtifact` type to allow the user to store arbitrary documentation related to their models.

**Comment by antisaling** [comment]
I also believe that HF metadata might be a useful reference for us, namely, the following classes:
- [`ModelInfo`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.hf_api.ModelInfo)
- [`RepoSibling`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.hf_api.RepoSibling) and [`RepoFile`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.hf_api.RepoFile)
- [`CardData`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/cards#huggingface_hub.ModelCardData)

**Comment by lampajr** [comment]
Hey @isinyaaa have you already started some working on this (from REST and Go side)? Otherwise I'll be happy to take it
