### ISSUE TITLE
Add kustomize manifest for installing model registry

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#269]
**Is your feature request related to a problem? Please describe.**
Add support for kustomize manifests to install model registry similar to the way kubeflow pipelines are installed. Kubeflow components are not installed using operators, but use manifest files instead. 

**Describe the solution you'd like**
Add kubeflow style kustomize manifests. Assume that mlmd would have been deployed as part of kubeflow pipelines install in a namespace. 

**Describe alternatives you've considered**
Kubeflow components do not support using operators for install. However, ODH can continue to use model-registry-operator to install model-registry. 

**Additional context**
None

**Comment by tarilabs** [comment]
Was done with:
- https://github.com/kubeflow/model-registry/commit/ec8618e4ec081028b71e431f429191ff888a07f5
- https://github.com/kubeflow/model-registry/commit/54b3792299a6d9dcdb6da8a0139c4fe089575616
