### ISSUE TITLE
Add auto-formatters

### ISSUE THREAD

**Issue by antisaling** [opendatahub-io/model-registry-bf4-kf#277]
Auto-formatters can reduce development overhead significantly, so we should adopt them for the languages used in the project.

**Comment by tarilabs** [comment]
I believe GoLang comes out of the box with the Linter? 🤔

**Comment by antisaling** [comment]
> I believe GoLang comes out of the box with the Linter? 🤔

As @lampajr pointed out, we don't need to include GoLang in this as `golangci-lint` is already configured for this purpose.
I think we should have something to format yaml/json, and maybe something for Python project-wide, to ensure we're covering most corners.
