### ISSUE TITLE
Automate Upstream Release Process

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#278]
Automate the community release process including the release of both 
- Python client
- Model registry server

This way we can assure the version are compatible.

A side note, right now we do have [2 version](https://github.com/opendatahub-io/model-registry/tags):
- Server: v0.1.0
- Python: py-v0.1.0
which have been released in different moments, so we might consider releasing a new python version, e.g., `v0.1.1` from the `main` branch

**Comment by tarilabs** [comment]
Checked with @lampajr this is Obsolete.

If anything, consider tagging at-once both as:
- [v0.1.2](https://github.com/opendatahub-io/model-registry/releases/tag/v0.1.2)
- [py-v0.1.2](https://github.com/opendatahub-io/model-registry/releases/tag/py-v0.1.2)

to get both issued in sync.
