### ISSUE TITLE
[feature][graphql] Create a tool to map metadata library to GraphQL schema

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#29]
**Is your feature request related to a problem? Please describe.**
Metadata libraries are defined in `yaml` files, they need to be mapped to `.graphqls` files for gqlgen to generate GraphQL model and resolvers. 

**Describe the solution you'd like**
A simple go tool to parse library `yaml` files and generate `graphqls` files. 

**Describe alternatives you've considered**
None

**Additional context**
The tool should also run automatically using Makefile rules.

**Comment by tarilabs** [comment]
closing as "not planned now" and labelled as requested, per Scrum decision 2023-10-30
