### ISSUE TITLE
Allow users to update a generic `Artifact`

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#297]
**Is your feature request related to a problem? Please describe.**
With this PR https://github.com/opendatahub-io/model-registry/pull/289 we extended the `Artifact` types with a new `DocArtifact`.

`DocArtifact` can be added using `versions/<id>/artifacts` endpoint but there is no way to update them once created, I think that it is worth to consider adding some endpoints for generic `get` and `patch` of a generic artifact.

**Describe the solution you'd like**
Add some endpoints for generic `get` and `patch` (and `post` ?) of a generic artifact.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by antisaling** [comment]
Superseded by: https://github.com/kubeflow/model-registry/issues/369
