### ISSUE TITLE
[feature][graphql] Create a tool to generate converters for GraphQL and DB model mapping

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#30]
**Is your feature request related to a problem? Please describe.**
Implementing GraphQL resolvers requires converting/mapping from GraphQL model structs to DB model structs and vice versa. 

**Describe the solution you'd like**
A simple tool can parse library metadata `yaml` files and generate converter code for the types defined in the library. This tool can do it along with generating `graphqls` schema files. 

**Describe alternatives you've considered**
Writing converters by hand does not scale and is hard to maintain when the metadata libraries change and grow. 

**Additional context**
A common tool can do schema and converter generation.

**Comment by tarilabs** [comment]
closing as "not planned now" and labelled as requested, per Scrum decision 2023-10-30
