### ISSUE TITLE
[feature][graphql] Create a tool to generate resolver mapping for gqlgen

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#31]
**Is your feature request related to a problem? Please describe.**
In GraphQL, nested types can have their own resolvers to support resolving child/related types. 
`gqlgen` uses a config file `gqlgen.yml` to generate GraphQL resolvers. This configuration is static in the file and has to be updated when new GraphQL type hierarchies are added. 

**Describe the solution you'd like**
A mapping generator tool that parses the library `yaml` files can also generate the resolver configuration required by `gqlgen`. 

**Describe alternatives you've considered**
Manually maintaing resolver configuration in the `gqlgen.yml` file will be time consuming and hard to keep in sync with metadata library changes. 

**Additional context**
The same tool that's generating GraphQL schema and converters from library definitions can also generate/update resolver configuration in `gqlgen.yml`.

**Comment by tarilabs** [comment]
closing as "not planned now" and labelled as requested, per Scrum decision 2023-10-30
