### ISSUE TITLE
Remove wrong copy right

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#41]
I see this in various files `Copyright © 2023 Dhiraj Bokde dhirajsb@gmail.com` that needs to be removed. Replace with `Copyright (c) 2023 Red Hat, Inc.`

It is probably OK not to have license header in each file as long as root directory contains the LICENSE file.

**Comment by tarilabs** [comment]
> It is probably OK not to have license header in each file as long as root directory contains the LICENSE file

That is my understanding too, as this project is not _inside_ the Apache foundation and ASL licensed is enough the root license file.

**Comment by dhirajsb** [comment]
BTW, I did create #9 to fix the license in at least top level files like `main.go`, and `cmd/*.go`. But nobody has volunteered yet. :wink:
