### ISSUE TITLE
Define logical schema model for Model Registry

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#45]
**Is your feature request related to a problem? Please describe.**
Need to define data model for model registry using MLMD

**Describe the solution you'd like**

Map the constructs of `RegisteredModel` and `VersionedModel` into logical constructs on top of MLMD model. 

Should we be defining this underneath OpenAPI layer?

**Comment by tarilabs** [comment]
@rareddy can you kindly link definitions of `RegisteredModel` and `VersionedModel` so to disambiguate/avoid misunderstanding, please?

**Comment by rareddy** [comment]
More information on this in https://github.com/opendatahub-io/model-registry/issues/44

The way I am seeing is a `RegisteredModel` is a model that has one more versioned models (context in mlmd?). It represents grouping of a single named Model. The name, labels, description etc is shared but exact model specifics like version, url are in the VersionedModel. Think like this as Model Card semantic from HF.

Registered Model ------> [] VersionedModel

Where as `VersionedModel`, is the end leaf mostly immutable that has specific versions like `version 1` , `version 2` and each version represents instance. Each one has a specific URL.

**Comment by tarilabs** [comment]
I believe you mean something like this: 

![image](https://github.com/opendatahub-io/model-registry/assets/1699252/42e00fda-6754-4141-9aaa-ca48e473ab4f)

Feel free to comment if o/w

**Comment by rareddy** [comment]
Yes, that is what I was thinking. A given tag  can only exist on only one versioned model. We need to think how we can support tag for A/B testing, but for now this is good IMO

I may have called `tag` as `stage` to bring clear distinction between `labels` and `tags`. We may also need some known labels like `new`, `ready for deployment`, `deploying`, `deployed`, `archived`, `deleted` or may be we can pull this into another property called `status` possibly the versioned model. Where Model Serving can poll on status = `ready for deployment` and deploy it to `stage` defined environment?

**Comment by rareddy** [comment]
https://miro.com/app/board/uXjVNeivrNY=/

**Comment by dhirajsb** [comment]
Closing as we have the model defined in REST API.
