### ISSUE TITLE
Create an Operator for Model Registry

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#47]
**Is your feature request related to a problem? Please describe.**

Model Registry needs a operator that can be used deploy Model Registry related resources in an OpenShift platform

**Describe the solution you'd like**

Design Go based operator using Opearator SDK for Model Registry. The deployment model should mimic much like what we see in Kustomize scripts https://github.com/kubeflow/kfp-tekton/tree/master/manifests/kustomize/base/metadata

The resulting YAML of Kusomize needs to be converted into Go constructs. Kustomize script directly calls the deployment on mySQL database, here may be we can add additional dereference and and call `Custom Resource` of MySQL operator otherwise switch this to PostgreSQL and use the Crunchy Operator for achieve the same.

**Comment by tarilabs** [comment]
See also: #15

**Comment by tarilabs** [comment]
I believe this can be closed, since:
- https://github.com/opendatahub-io/model-registry-operator/pull/54
- https://github.com/opendatahub-io/opendatahub-operator/pull/776#event-11667004839

Productizations are already tracked in JIRAs.

Kindly consider Close.

**Comment by tarilabs** [comment]
@dhirajsb @rareddy 

I believe this can be closed, since:

- https://github.com/opendatahub-io/model-registry-operator/pull/54
- https://github.com/opendatahub-io/opendatahub-operator/pull/776#event-11667004839
- 
Productizations are already tracked in JIRAs.

Kindly consider Close.
