### ISSUE TITLE
Integrate Model Registry issues into ODH dashboard

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#53]
Need to integrate Model Registry issues in the ODH dashboard. For that automatically take place we need to add the following [YAML file](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/auto-add-issue-to-project.yml) in the repo

**Comment by lampajr** [comment]
Maybe we should first create the Model Registry Dashboard project here https://github.com/orgs/opendatahub-io/projects?query=is%3Aopen as I see there are projects specific for each area, wdyt?

Something like `ODH Model Registry Planning`

**Comment by tarilabs** [comment]
@rareddy let us know which Dashboard (by providing link) or which new to be created then we can create PR with the file

**Comment by rareddy** [comment]
right, creating the project as @lampajr suggested, want to make sure that is what is needed by the other team

**Comment by tarilabs** [comment]
will proceed by creating a Dashboard as Andrea mentioned, will sink with Serving if there is any "cross-dashboard" needed.

**Comment by rareddy** [comment]
https://github.com/orgs/opendatahub-io/projects/49 it is private now looking to how I make it public

**Comment by rareddy** [comment]
@tarilabs  Can we update the file details like this here https://github.com/opendatahub-io/odh-dashboard/pull/1899/files see how step one generates the token in there and used by the project in next step.

Template here https://github.com/red-hat-data-services/rhods-devops-infra/blob/main/.github/workflows/auto-add-issues-to-project.yaml

The secrets will be taken from org's secrets

**Comment by tarilabs** [comment]
@rareddy updating as requested in https://github.com/opendatahub-io/model-registry/pull/56
