### ISSUE TITLE
Add SNYK scan for the repository

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#62]
https://app.snyk.io/ 

We need to Synk scan on the repository set up to discover any vulnerabilities we may pull in. Check other projects in ODH space how they were able to configure this. Also do for the Operator repository

@vaibhavjainwiz can help with the setup

**Comment by tarilabs** [comment]
Work on https://github.com/opendatahub-io/model-registry/issues/50 is likely also a good prereq to be wired-up with Snyk

**Comment by tarilabs** [comment]
Seems to me we need first the "forks" in the https://github.com/red-hat-data-services of the upstream ODH repos as prerequisite.

Therefore, seems to me another prerequisite is: Productization is happening (for model-registry, and related repos if any).

**Comment by rareddy** [comment]
not un upstream issue (see [RHOAIENG-1824](https://issues.redhat.com//browse/RHOAIENG-1824))
