### ISSUE TITLE
Evaluate PostgreSQL Server as backend to use with ml-metadata

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#65]
I have just learned that ml-metadata does put in support for PostgreSQL from the Kubeflow Summit presentation. We need to explore the solution and figure out what it takes to adapt to it.

**Comment by tarilabs** [comment]
@rareddy I was attending too and I guess you mean 
![Screenshot_20231006_194943](https://github.com/opendatahub-io/model-registry/assets/1699252/fdddf327-a526-4bf6-b3ee-d5c69725f192)

When I follow link however 
`https://github.com/kubeflow/pipelines/issues/9813`

I'm still a bit confused as from the tracker (at the time of writing) some work is still in flux

**Comment by rareddy** [comment]
the speaker mentioned the feature was done, so we just need to experiment with it and figure out t can be used if not we can provide the feedback in the community.

**Comment by tarilabs** [comment]
By the way, found this which is a bit more promising: https://github.com/google/ml-metadata/blob/de25304b6d123e3044b64be9ceaf979f61483fe5/RELEASE.md?plain=1#L20

Didn't found explicit documentation about it, so I'm planning to give it a try by just running data connection configuration and see what happens

**Comment by tarilabs** [comment]
@rareddy I have a demo ready with https://github.com/tarilabs/demo20231009-mlmdpg#readme

Assuming the following acceptance criteria for this GH issue:
- [x] demonstrate ml-metadata Python library connects to PostgreSQL directly
- [x] demonstrate ml-metadata Python library connects to ml-metadata server via gRPC, and for the ml-metadata server to connect to PostgreSQL

I would close this issue as resolved.
I can demo in a call if preferred.

**Comment by tarilabs** [comment]
👉 https://github.com/opendatahub-io/model-registry/issues/65#issuecomment-1761606779
