### ISSUE TITLE
Use named sub-types for `MetadataValue` property value types

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#74]
**Is your feature request related to a problem? Please describe.**
Using anonymous sub-types in `MetadataValue` is causing openapi-generator create structs with names like `model_metadata_value_one_of_*.go`.

**Describe the solution you'd like**
Using named sub-types will make using different property value types easier and meaningful. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tarilabs** [comment]
added into sprint as a PR is already available, thank you 🙏
