### ISSUE TITLE
Develop REST Server with OpenAPI Contract defined in Go

### ISSUE THREAD

**Issue by tarilabs** [opendatahub-io/model-registry-bf4-kf#90]
**Is your feature request related to a problem? Please describe.**
The Core layer needs to be wired to the OpenAPI codegen

**Describe the solution you'd like**
Acceptance criteria:
- Wiring Core layer in Go through the "stubs" generated under `internal/server/openapi/api_model_registry_service_service.go`
- Demonstrate with test going through the REST interface (eg: Robot Framework, if possible)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rareddy** [comment]
is this duplicate to #59?

**Comment by tarilabs** [comment]
> is this duplicate to #59?

@rareddy fair, moving "acceptance criteria" from here to #59
