### ISSUE TITLE
Skip PR checks when not needed

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#93]
If we are changing files for which we do not have to perform any kind of check, e.g, if we are changing ISSUE_TEMPLATE or just doc files, we should skip GitHub workflow trigger.

**Comment by tarilabs** [comment]
+1, as @isinyaaa previously suggested we could ignore GHA running when modification happens in specific directories, or specific file extensions (eg: `.md`)
