### ISSUE TITLE
[Tracker]: Model Registry - MVP

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#95]
### Description

Design and develop a "Model Registry" solution in the RHODS.

A model registry provides a repository for model developers to store and manage models, versions, and model metadata. It fills a gap between model experimentation and model serving activities. It provides a central interface for stakeholders in the ML life cycle to collaborate on models securely, optimizing the overall efficiency of the MLOps workflow.

### Target Branch

tbd

### Requirements

[Requirements doc #1](https://docs.google.com/document/d/1mRUQ9C5Br7T3bA49H503HTq0J7F4WKySdxaWpTX-i8k/edit) 
[Requirements doc #2](https://docs.google.com/document/d/1XT0PxVp78VEyeMXKkF5qrP-fdgN4V_G9UxH2a1OpPY8/edit#heading=h.vk5ku8fmql4y)
[Proposal doc](https://docs.google.com/document/d/1G-pjdGaS2kLELsB5kYk_D4AmH-fTfnCnJOhJ8xENjx0/edit#heading=h.ds8q4xtkmu64)

### Itemized UX Issues

https://github.com/opendatahub-io/odh-dashboard/issues/1804

### Itemized Dev Issues

* #44
* #58
* #70 
  * https://github.com/opendatahub-io/model-registry/issues/107
* #61 
* #90 
* #60 
* #59 
* #47 
* #46 
* #45 
* https://github.com/opendatahub-io/model-registry/issues/65
* #96
* #137 
* #129 
* #130 
*

**Comment by tarilabs** [comment]
@rareddy https://github.com/opendatahub-io/model-registry/issues/10 is not needed here, as that pertained to "rewrite everything in Go" so might go in another tracker.
I've replaced it instead with https://github.com/opendatahub-io/model-registry/issues/65 which was the research to check MLMD worked with PostgreSQL after announce at KubeFlow Summit conference.
If my replacement was not-correct, kindly undo and my apologies

**Comment by tarilabs** [comment]
migrated to https://issues.redhat.com/browse/RHOAIENG-1797
